# Generated by Django 4.0.5 on 2022-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_code',
            field=models.CharField(default='fa-nothin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
